import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TopLoaderProvider } from "@/context/TopLoader";
import { SidebarProvider } from "@/context/SidebarContext";
import ConfirmationPopup from "@/components/common/ConfirmationPopup";
import { PopupProvider } from "@/context/PopupContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopLoaderProvider>
          <PopupProvider>
            <SidebarProvider>
              {children}
              <Toaster position="bottom-right" />
              <ConfirmationPopup />
            </SidebarProvider>
          </PopupProvider>
        </TopLoaderProvider>
      </body>
    </html>
  );
}
